age fun for postgresql
promise-labs/arrow-datafusion pull request #37
Opened 2023-11-30 03:55 UTC by xiaoyumoyu

## Which issue does this PR close?
none

Closes #.

## Rationale for this change
implement age function for postgresql

## What changes are included in this PR?
add age function

## Are these changes tested?
yes

## Are there any user-facing changes?
no

2023-11-30 04:04 UTC, wizardxz requested changes

2023-11-30 04:04 UTC, wizardxz commented on extension/functions/src/postgres.rs
> +// use arrow::array::{ArrayRef, BooleanArray, Int64Array,StringBuilder,Float64Array};
rm

2023-11-30 04:04 UTC, wizardxz commented on extension/functions/src/postgres.rs
> +                DataType::Timestamp(TimeUnit::Nanosecond, None),
could also be second/millisecond/microsecond

2023-11-30 05:16 UTC, wizardxz commented on extension/functions/src/postgres.rs
> +                DataType::Timestamp(TimeUnit::Nanosecond, None),
As long as test works, I think it is fine to only have nanosecond cc @sadboy

2023-11-30 19:39 UTC, sadboy commented on extension/functions/src/postgres.rs
> +                DataType::Timestamp(TimeUnit::Nanosecond, None),
This should match the default timeunit of Postgres right? (I haven't checked what that is)

2023-11-30 19:42 UTC, sadboy commented on extension/functions/src/postgres.rs
> +pub struct AgeFunction;
Could you add a link to the function in Postgres doc? That makes it easier to cross reference the source of truth. 
e.g.
```suggestion
/// Postgres `age` function ([link to doc])
pub struct AgeFunction;
```

2023-11-30 20:01 UTC, wizardxz approved these changes

2023-11-30 20:04 UTC, wizardxz commented on extension/functions/src/postgres.rs
> +                DataType::Timestamp(TimeUnit::Nanosecond, None),
The default is the microsecond. But looks like DF has type coercion from any timeunit to Nanosecond. So I think it is fine after I look at the tests

2023-11-30 20:05 UTC, wizardxz commented on extension/functions/src/postgres.rs
> +pub struct AgeFunction;
Great point! cc @xiaoyumoyu

2023-12-01 03:00 UTC, xiaoyumoyu commented on extension/functions/src/postgres.rs
> +pub struct AgeFunction;
ok！Should I submit it again right away after making the additions？

2023-12-01 04:51 UTC, merged